# Site settings

# Build settings
markdown: kramdown
permalink: pretty

include:
  - .nojekyll

exclude:
  - package.json
  - bower.json
  - bower_components
  - README.md
  - CNAME
  - bower.json

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (using font awesome for icons )
social:
  - title: twitter
    url: http://twitter.com/daplanet
  - title: linkedin
    url: http://linkedin.com/company/daplanet
  - title: github
    url: http://github.com/daplanet
  - title: stack-overflow
    url: http://careers.stackoverflow.com/company/daplanet

email: sales@dapla.net

# SEO Meta data ( works with page frontmater )
meta:
  title: Da Planet Security
  description: >
  The leader in cloud security and big data analytics, Da Planet Security is the ideal managed security solutions provider.

# Social Media tags ( works with page frontmater )
opengraph:
  title: Leaders in Cloud Security and Big Data analytics.
  type: article
  image:
  description: >
  The leader in cloud security and big data analytics, Da Planet Security is the ideal managed security solutions provider.
  site_name: Da Planet Security
  fb_admins:
